/**
 * Illustrative Industry Solution workspace: the industry's own navigation
 * (Overview + modules + Workflows/Reports/Settings, as generated by the platform),
 * a workflow stepper from its real workflow definition, and the Business Apps it
 * builds on. Counts are illustrative.
 */
import { CalendarClock, ChartColumn, GitBranch, LayoutDashboard, Settings } from "lucide-react";
import type { Industry } from "@/data/industries";
import { productById } from "@/data/products";
import { Icon } from "@/lib/icons";
import { cn, tint } from "@/lib/utils";
import { MockFrame } from "./WorkspaceMock";

const SAMPLE = [128, 42, 17, 9, 64, 23, 11, 36, 5, 88];

export function IndustryWorkspaceMock({ industry, className, chrome = true }: { industry: Industry; className?: string; chrome?: boolean }) {
  const a = industry.accent;
  const nav = ["Overview", ...industry.modules.slice(0, 7), "Workflows", "Reports", "Settings"];
  const wf = industry.workflows[0];
  return (
    <MockFrame className={className} chrome={chrome} url={`app.melorite.com/${industry.slug}`}>
      <div className="flex h-[5.4em] items-center justify-between border-b border-[#e8edf3] px-[2em]">
        <span className="flex items-center gap-[1em]">
          <span className="grid size-[3.2em] place-items-center rounded-[0.8em]" style={{ background: tint(a, 0.12), color: a }}>
            <Icon name={industry.icon} className="size-[1.7em]" />
          </span>
          <span className="text-[1.6em] font-semibold text-[#0a2540]">{industry.fullName}</span>
        </span>
        <span className="flex items-center gap-[0.6em] text-[1.2em] text-[#64748b]">
          <span className="rounded-[0.5em] px-[0.7em] py-[0.25em] ring-1 ring-[#e3e8ef]">Northwind Group</span>
          <span className="rounded-[0.5em] px-[0.7em] py-[0.25em] font-medium text-white" style={{ background: "#2563eb" }}>New</span>
        </span>
      </div>
      <div className="flex">
        <aside className="w-[21em] shrink-0 border-r border-[#e8edf3] py-[1.4em]">
          <ul className="space-y-[0.25em] px-[1em]">
            {nav.map((m, i) => {
              const on = i === 0;
              const I = i === 0 ? LayoutDashboard : m === "Workflows" ? GitBranch : m === "Reports" ? ChartColumn : m === "Settings" ? Settings : CalendarClock;
              return (
                <li key={m} className={cn("flex h-[3.3em] items-center gap-[0.9em] rounded-[0.6em] px-[1em] text-[1.3em]", !on && "text-[#475569]")} style={on ? { background: tint(a, 0.09), color: a, fontWeight: 600 } : undefined}>
                  {i === 0 || i > industry.modules.slice(0, 7).length ? <I className="size-[1.1em]" aria-hidden /> : <i className="size-[0.55em] rounded-full" style={{ background: tint(a, 0.5) }} />}
                  <span className="truncate text-[0.95em]">{m}</span>
                </li>
              );
            })}
          </ul>
        </aside>
        <div className="min-w-0 flex-1 space-y-[1.6em] p-[2.2em]">
          <div>
            <div className="font-mono text-[1em] uppercase tracking-[0.14em] text-[#64748b]">Industry workspace</div>
            <div className="text-[2.4em] font-semibold tracking-[-0.02em] text-[#0a2540]">Overview</div>
          </div>
          <div className="grid grid-cols-4 gap-[1em]">
            {industry.modules.slice(0, 4).map((m, i) => (
              <div key={m} className="rounded-[0.9em] p-[1.4em] ring-1 ring-[#e3e8ef]" style={i === 0 ? { background: tint(a, 0.05) } : undefined}>
                <div className="truncate text-[1.15em] text-[#64748b]">{m}</div>
                <div className="mt-[0.3em] text-[2.3em] font-semibold tracking-[-0.02em] text-[#0a2540]">{SAMPLE[i]}</div>
              </div>
            ))}
          </div>
          <div className="rounded-[0.9em] p-[1.8em] ring-1 ring-[#e3e8ef]">
            <div className="mb-[1.6em] flex items-center justify-between text-[1.25em]">
              <span className="font-semibold text-[#0a2540]">{wf.name}</span>
              <span className="text-[#64748b]">Workflow</span>
            </div>
            <div className="flex items-start">
              {wf.steps.map((s, i) => (
                <div key={s} className="flex min-w-0 flex-1 flex-col items-center">
                  <div className="flex w-full items-center">
                    <span className={cn("h-[0.2em] flex-1", i === 0 && "invisible")} style={{ background: i <= 2 ? a : "#e2e8f0" }} />
                    <span className="grid size-[2.4em] shrink-0 place-items-center rounded-full text-[1em] font-semibold" style={i <= 2 ? { background: a, color: "#fff" } : { background: "#fff", color: "#94a3b8", boxShadow: "inset 0 0 0 0.15em #e2e8f0" }}>
                      {i + 1}
                    </span>
                    <span className={cn("h-[0.2em] flex-1", i === wf.steps.length - 1 && "invisible")} style={{ background: i < 2 ? a : "#e2e8f0" }} />
                  </div>
                  <span className="mt-[0.7em] line-clamp-2 px-[0.3em] text-center text-[1.05em] leading-tight text-[#475569]">{s}</span>
                </div>
              ))}
            </div>
          </div>
          <div className="flex flex-wrap items-center gap-[0.6em]">
            <span className="mr-[0.4em] text-[1.15em] text-[#64748b]">Built on</span>
            {industry.apps.slice(0, 8).map((id) => {
              const p = productById(id)!;
              return (
                <span key={id} className="inline-flex items-center gap-[0.4em] rounded-full bg-white px-[0.8em] py-[0.3em] text-[1.1em] font-medium text-[#0a2540] ring-1 ring-[#e3e8ef]">
                  <Icon name={p.icon} className="size-[1em]" style={{ color: p.accent }} />
                  {p.shortName}
                </span>
              );
            })}
          </div>
        </div>
      </div>
    </MockFrame>
  );
}
