import { notFound } from "next/navigation";
import AppPage from "@/components/AppPage";

const APPS = {
  "crm-sales": { name: "CRM & Sales", eyebrow: "CRM & Sales", title: "Turn every opportunity into connected growth", lede: "Manage leads, customers, opportunities, activities and follow-ups from one sales workspace while keeping the rest of the business connected to the customer journey.", image: "/assets/img/melorite/crm-sales.png", featuresHead: "A complete customer workspace", featuresCopy: "Keep the customer journey connected from the first enquiry through delivery and long-term account management.", connected: "When a deal moves forward, relevant customer context can flow into projects, finance, operations and support.", features: [{ title: "Capture every opportunity", body: "Centralise enquiries, leads and prospect information." }, { title: "Build one customer view", body: "Keep contacts, organisations, interactions and activities together." }, { title: "Manage your pipeline", body: "Track deals through configurable stages and ownership." }, { title: "Never lose the next action", body: "Connect tasks, meetings, reminders and follow-ups directly to customers and opportunities." }, { title: "Understand performance", body: "Monitor pipeline, conversion, activity and forecasting from shared dashboards." }] },
  "finance-accounting": { name: "Finance & Accounting", eyebrow: "Finance & Accounting", title: "Finance that understands the business behind the numbers", lede: "Connect financial workflows with customers, projects, teams and operational activity so finance has the context required to make better decisions.", image: "/assets/img/melorite/hero-platform.png", featuresHead: "Financial operations with context", featuresCopy: "Structure financial workflows around the work, customers and responsibilities behind every transaction.", connected: "Melorite is designed to connect financial processes with the commercial and operational context that creates them.", features: [{ title: "Billing & invoicing", body: "Manage billing processes connected to customers and work delivered." }, { title: "Receivables", body: "Track outstanding payments and customer balances." }, { title: "Expenses & payables", body: "Record and manage business expenses and outgoing obligations." }, { title: "Financial visibility", body: "Understand performance through connected financial dashboards." }, { title: "Controls", body: "Use roles, approvals and permissions to structure financial responsibilities." }] },
  "people-payroll": { name: "People & Payroll", eyebrow: "People & Payroll", title: "Manage your people as part of the business, not a separate system", lede: "Bring employee information, attendance, leave, payroll workflows and organisational responsibilities into the same connected environment as everyday operations.", image: "/assets/img/melorite/hero-platform.png", featuresHead: "One people workspace", featuresCopy: "Keep your people operations connected to the teams, roles and day-to-day work they support.", connected: "People records, organisation structure and responsibilities can stay aligned with the wider Melorite platform.", features: [{ title: "Employee records", body: "Maintain a reliable people record for every employee." }, { title: "Organisation structure", body: "Connect teams, roles and responsibilities." }, { title: "Attendance & leave", body: "Manage attendance and leave processes in context." }, { title: "Payroll workflows", body: "Structure the steps and approvals around payroll." }, { title: "Roles & permissions", body: "Give people the access appropriate to their responsibilities." }] },
  "projects-operations": { name: "Projects & Operations", eyebrow: "Projects & Operations", title: "Turn plans into coordinated execution", lede: "Plan projects, assign responsibilities, organise tasks and keep operational work connected with customers, teams and business priorities.", image: "/assets/img/melorite/hero-platform.png", featuresHead: "Make execution visible", featuresCopy: "Coordinate the work behind your business through clear ownership, workflows and shared progress.", connected: "Operational work stays connected to the customers, teams and business priorities it supports.", features: [{ title: "Projects & milestones", body: "Plan structured delivery from major outcomes to key checkpoints." }, { title: "Tasks & dependencies", body: "Clarify ownership, timing and dependencies." }, { title: "Workloads", body: "Understand team capacity and responsibilities." }, { title: "Recurring processes", body: "Coordinate repeatable operational work." }, { title: "Progress tracking", body: "Use shared dashboards to see what needs attention." }] },
  "customer-support": { name: "Customer Support", eyebrow: "Customer Support", title: "Support customers with the full story in view", lede: "Manage customer questions, requests and issues while keeping support connected with the customer information already available across Melorite.", image: "/assets/img/melorite/crm-sales.png", featuresHead: "Service with full context", featuresCopy: "Give support teams the customer history, ownership and connected operational context they need.", connected: "Support does not need to operate separately from sales, operations or account information.", features: [{ title: "Tickets & assignment", body: "Capture, prioritise and route customer requests." }, { title: "Status workflows", body: "Keep the next action and owner clear." }, { title: "Conversation history", body: "Maintain a connected record of customer communication." }, { title: "Customer context", body: "See the wider relationship behind each request." }, { title: "Service metrics", body: "Monitor service performance and escalations." }] },
  marketing: { name: "Marketing", eyebrow: "Marketing", title: "Connect marketing activity to the rest of the customer journey", lede: "Plan campaigns, organise marketing activity, manage audiences and connect marketing outcomes with leads, customers and revenue.", image: "/assets/img/melorite/crm-sales.png", featuresHead: "Marketing in business context", featuresCopy: "Keep campaign planning, audience activity and outcomes connected to the rest of the organisation.", connected: "Marketing can work from the same customer and commercial context as sales and service teams.", features: [{ title: "Campaign management", body: "Plan activity around clear outcomes and ownership." }, { title: "Audience organisation", body: "Organise the audiences your business serves." }, { title: "Lead capture", body: "Connect early interest with the sales journey." }, { title: "Content workflows", body: "Coordinate approvals, tasks and campaign delivery." }, { title: "Campaign reporting", body: "Understand outcomes alongside CRM and commercial context." }] },
};
export function generateStaticParams() { return Object.keys(APPS).map((slug) => ({ slug })); }
export function generateMetadata({ params }) { const app = APPS[params.slug]; return { title: app ? `${app.name} | Melorite` : "Melorite" }; }
export default function Page({ params }) { const app = APPS[params.slug]; if (!app) notFound(); return <AppPage app={app} />; }
