import Link from "next/link";
import { businessApplications, industrySolutions } from "@/data/catalog";
import { Icon } from "@/lib/icons";
import { tint } from "@/lib/utils";
import { NavigationMenuLink } from "@/components/ui/navigation-menu";
import { Arrow } from "@/components/shared/Button";
function Item({ href, title, description, icon = "ArrowUpRight", accent = "#2563eb" }: { href: string; title: string; description: string; icon?: string; accent?: string }) { return <NavigationMenuLink asChild><Link href={href} className="group flex-row items-start gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-lg" style={{ background: tint(accent,.1), color: accent }}><Icon name={icon} className="size-4" /></span><span><span className="block text-sm font-medium text-navy">{title}</span><span className="block text-[12.5px] leading-5 text-muted">{description}</span></span></Link></NavigationMenuLink>; }
function Menu({ children, href, label, wide = true }: { children: React.ReactNode; href: string; label: string; wide?: boolean }) { return <div className={`${wide ? "w-[min(820px,calc(100vw-3rem))]" : "w-[360px]"} p-6`}><div className={wide ? "grid grid-cols-2 gap-x-6 gap-y-1" : "space-y-1"}>{children}</div><NavigationMenuLink asChild><Link href={href} className="group mt-5 inline-flex items-center gap-1.5 text-sm font-medium text-brand hover:bg-transparent hover:text-brand-700">{label} <Arrow /></Link></NavigationMenuLink></div>; }
export function ProductsMenu() { return <Menu href="/products" label="View all Products"><div className="col-span-2 mb-1 px-2 text-[11px] font-semibold uppercase tracking-[.1em] text-slate-400">Business Applications</div>{businessApplications.map(x => <Item key={x.slug} href={`/products/${x.slug}`} title={x.name} description={x.eyebrow} icon={x.icon} accent={x.accent} />)}<div className="col-span-2 mt-3 mb-1 px-2 text-[11px] font-semibold uppercase tracking-[.1em] text-slate-400">Melorite AI</div><Item href="/ai/agent" title="AI Agent" description="Intelligence and automation across your organization." icon="Sparkles" /><Item href="/ai/calling" title="AI Calling" description="AI-powered inbound and outbound business conversations." icon="PhoneCall" accent="#7c3aed" /></Menu>; }
export function SolutionsMenu() { return <Menu href="/solutions" label="Explore all Solutions">{industrySolutions.map(x => <Item key={x.slug} href={`/solutions/${x.slug}`} title={x.name} description="Connected workflows for your industry." icon={x.icon} accent={x.accent} />)}</Menu>; }
export function CompanyMenu() { return <Menu wide={false} href="/company" label="About Melorite"><Item href="/company" title="About Melorite" description="Our platform philosophy and approach." /><Item href="/resources" title="Resources" description="Insights and product guidance." icon="BookOpen" accent="#7c3aed" /><Item href="/company#careers" title="Careers" description="Join the team behind Melorite." icon="Briefcase" accent="#059669" /><Item href="/contact" title="Contact" description="Speak with the Melorite team." icon="Mail" accent="#ea580c" /></Menu>; }
