'use client';
import {useState,useEffect,useRef} from 'react';
import {ArrowUpRight,ArrowRight,ChevronDown,Menu,X,Check,Layers,Workflow,BarChart3,Users,BriefcaseBusiness,Wallet,CircleHelp,Package,HeartHandshake,Building2,Boxes,FileText,CalendarDays,ChartNoAxesCombined,Mail,Settings2,ShieldCheck,Globe,Plus,Minus} from 'lucide-react';
const apps=['CRM','Sales','Finance','Procurement','Inventory','HR','Payroll','Projects','Service','Marketing & Campaigns','Operations','Documents','Automation','Analytics'];
const industries=['Hospital Management','Clinic Management','Real Estate','Education','Manufacturing','Construction','Hospitality','Retail','Logistics & Transport','Distribution','Professional Services','Recruitment & Staffing','Facility Management','Automotive Service','Nonprofit & Association'];
const menus:Record<string,string[]>={'Platform':['Overview','Business Apps','Industry Solutions','Integrations','Automation','Analytics'],'Business Apps':apps,'Industry Solutions':industries,'Resources':['Documentation','Help Center','Guides','Blog','Changelog'],'Company':['About Melorite','Our Mission','Contact','Careers']};
const appDescriptions:Record<string,string>={CRM:'Build stronger relationships, from the first hello to your next opportunity.',Sales:'Give your sales team a clear path from opportunity to order.',Finance:'Bring your invoices, expenses, and financial overview together.',Procurement:'Keep purchasing, supplier relationships, and approvals connected.',Inventory:'See what is in stock and keep every movement in view.',HR:'Put your people, employee records, and daily HR work in one place.',Payroll:'Connect payroll preparation with the employee information behind it.',Projects:'Keep your team, tasks, and project milestones moving together.',Service:'Organize service requests and give your customers a smoother experience.','Marketing & Campaigns':'Plan campaigns and connect your marketing activity with customer relationships.',Operations:'Bring the moving parts of everyday business into a shared workspace.',Documents:'Keep your business documents organized and easier to find.',Automation:'Connect routine steps into repeatable workflows with clear handoffs.',Analytics:'Turn shared business information into a clearer picture of performance.'};
function Mark(){return <span className="brand-mark" aria-hidden="true"><i/><i/><i/><i/></span>}
export default function Home(){
 const [open,setOpen]=useState<string|null>(null); const [mobile,setMobile]=useState(false); const [detail,setDetail]=useState<string|null>(null);const [group,setGroup]=useState('Customer & growth');const [quote,setQuote]=useState(false);const [faq,setFaq]=useState<number|null>(0);const navRef=useRef<HTMLElement>(null);const dialogRef=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const close=(e:MouseEvent)=>{if(navRef.current&&!navRef.current.contains(e.target as Node))setOpen(null)};document.addEventListener('click',close);return()=>document.removeEventListener('click',close)},[]);
 useEffect(()=>{if(detail)dialogRef.current?.showModal();else dialogRef.current?.close()},[detail]);
 function select(item:string){setOpen(null);setMobile(false);const anchors:Record<string,string>={'Overview':'platform','Business Apps':'apps','Industry Solutions':'industries','Integrations':'connected','Automation':'connected','Analytics':'connected','About Melorite':'company','Our Mission':'company','Contact':'quote'}; if(anchors[item])document.getElementById(anchors[item])?.scrollIntoView({behavior:'smooth'});else setDetail(item)}
 return <><header ref={navRef} className="header"><a href="#" className="brand" aria-label="Melorite home"><Mark/>melorite<span className="brand-dot">®</span></a><nav className={mobile?'nav mobile-open':'nav'} aria-label="Main navigation">{Object.entries(menus).map(([name,items])=><div className="nav-group" key={name}><button className={open===name?'nav-trigger active':'nav-trigger'} aria-expanded={open===name} aria-controls={'menu-'+name.replaceAll(' ','-')} onClick={()=>setOpen(open===name?null:name)} onKeyDown={e=>{if(e.key==='Escape')setOpen(null)}}>{name}<ChevronDown size={12}/></button>{open===name&&<div id={'menu-'+name.replaceAll(' ','-')} className={'dropdown '+(items.length>8?'wide':'')}><div className="dropdown-intro"><span className="eyebrow">EXPLORE MELORITE</span><h3>{name}</h3><p>Everything your business needs.<br/>Connected by design.</p></div><div className="dropdown-links">{items.map(item=><button key={item} onClick={()=>select(item)}>{item}<ArrowUpRight size={14}/></button>)}</div></div>}</div>)}<div className="mobile-actions"><button onClick={()=>setDetail('Sign In')}>Sign In</button><a href="#quote" onClick={()=>setMobile(false)}>Get a Quote →</a></div></nav><div className="nav-actions"><button className="sign-in" onClick={()=>setDetail('Sign In')}>Sign In</button><a className="button small" href="#quote">Get a Quote <ArrowUpRight size={15}/></a></div><button className="menu-toggle" aria-label={mobile?'Close navigation':'Open navigation'} aria-expanded={mobile} onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button></header>
 <main><section className="hero" id="platform"><div className="hero-inner"><div className="hero-copy"><div className="eyebrow"><span className="tiny-cross">✳</span> THE CONNECTED BUSINESS PLATFORM</div><h1>Your business.<br/>Working <span>as one.</span></h1><p>Bring your people, processes, and possibilities<br className="desktop-break"/> together. One connected platform, built around<br className="desktop-break"/> the way you do business.</p><div className="hero-actions"><a className="button" href="#quote">Let’s build your solution <ArrowUpRight size={17}/></a><a className="text-link" href="#apps">Explore the platform <ArrowRight size={16}/></a></div><div className="hero-note"><span>14 business apps</span><i/><span>15 industry solutions</span><i/><span>One Melorite</span></div></div></div><div className="hero-photo"><img src="/office.jpg" alt="A bright, sunlit workspace for a connected team"/><div className="photo-shade"/><div className="floating-card task-card"><div className="card-top"><span className="mini-icon"><Workflow size={16}/></span><span>Less busywork. More momentum.</span><span className="card-time">Just now</span></div><div className="workflow-line"><span>New deal</span><ArrowRight size={12}/><span>Project created</span><ArrowRight size={12}/><span>Team notified</span></div><div className="card-bottom"><Check size={12}/> Connected with Melorite</div></div><div className="floating-card note-card"><span className="mini-icon"><Layers size={17}/></span><div>Your whole business.<br/><strong>Finally on the same page.</strong></div><span className="card-spark">✳</span></div><span className="photo-caption">A LITTLE MORE FLOW. A LOT MORE POSSIBILITY.</span></div></section>
 <section className="platform-strip"><p>From your first customer<br/>to your next chapter.</p><div><Users/>Customer relationships</div><div><Wallet/>Business essentials</div><div><Workflow/>Everyday operations</div><div><ChartNoAxesCombined/>Your next big move</div></section>
 <section className="section intro" id="apps"><div className="eyebrow blue">ONE PLATFORM. EVERY PART OF YOUR BUSINESS.</div><div className="section-heading"><h2>Great work happens<br/>when everything connects.</h2><p>Less switching between tools. More moving forward.<br/>Start with the apps you need and bring the rest<br/>together as your business grows.</p></div></section>
 </main><footer><a href="#" className="brand"><Mark/>melorite</a><p>Your business, working as one.</p><span>© {new Date().getFullYear()} Melorite</span></footer>
 <dialog ref={dialogRef} onCancel={()=>setDetail(null)} onClick={e=>{if(e.target===e.currentTarget)setDetail(null)}}><button className="dialog-close" aria-label="Close dialog" onClick={()=>setDetail(null)}><X/></button><div className="eyebrow blue">MELORITE</div><h2>{detail}</h2><p>{detail==='Sign In'?'Already using Melorite? Open the workspace link supplied by your organization or contact your workspace administrator.':appDescriptions[detail||'']||'Talk with us about '+detail?.toLowerCase()+' and how Melorite can support your team.'}</p><button className="button" onClick={()=>{setDetail(null);document.getElementById('quote')?.scrollIntoView({behavior:'smooth'})}}>Talk to Melorite <ArrowUpRight size={16}/></button></dialog></>;
}
