const sidebarItems = ["Home", "CRM", "Sales", "Projects", "Finance", "People", "Operations", "Support", "Analytics"];
const activities = [["New lead assigned", "CRM", "sky"], ["Invoice paid", "Finance", "mint"], ["Project updated", "Projects", "lavender"]];

export default function MeloriteDashboard() {
  return <div className="mel-dashboard" aria-label="Melorite connected business dashboard preview">
    <aside className="mel-sidebar"><div className="mel-app-mark"><span /> Melorite</div>{sidebarItems.map((item, index) => <div className={`mel-side-item${index === 0 ? " active" : ""}`} key={item}><i />{item}</div>)}</aside>
    <div className="mel-main"><div className="mel-topbar"><div className="mel-search">⌕&nbsp; Search workspace</div><div className="mel-top-actions"><span>⌁</span><span className="mel-avatar">MK</span></div></div><div className="mel-content"><div className="mel-welcome"><div><p>Monday, September 14</p><h3>Good morning, Maya</h3></div><button>+ Create new</button></div><div className="mel-stat-grid"><div><span>Revenue this month</span><strong>$84,200</strong><em>↗ 12.4%</em></div><div><span>Active pipeline</span><strong>$126,800</strong><em>↗ 8.2%</em></div><div><span>Open tasks</span><strong>24</strong><em className="neutral">Across 6 projects</em></div></div><div className="mel-board"><div className="mel-board-head"><div><span>Projects overview</span><small>Updated just now</small></div><button>View all</button></div><div className="mel-row mel-row-label"><span>Project</span><span>Owner</span><span>Status</span><span>Progress</span></div><div className="mel-row"><b>Website launch</b><span className="mel-person">Maya</span><span className="mel-status progress">In progress</span><span className="mel-progress"><i style={{ width: "72%" }} /></span></div><div className="mel-row"><b>Q4 campaign</b><span className="mel-person">Sam</span><span className="mel-status review">In review</span><span className="mel-progress"><i style={{ width: "54%" }} /></span></div><div className="mel-row"><b>Client onboarding</b><span className="mel-person">Lee</span><span className="mel-status done">Done</span><span className="mel-progress"><i style={{ width: "100%" }} /></span></div></div></div></div>
    <div className="mel-float float-lead"><span className="float-dot blue" />New lead <b>Northstar Co.</b></div><div className="mel-float float-automation"><span className="float-dot violet" />Automation triggered <b>Invoice follow-up</b></div><div className="mel-activity"><span>Live activity</span>{activities.map(([title, area, color]) => <div key={title}><i className={color} /> <b>{title}</b><small>{area}</small></div>)}</div>
  </div>;
}
