import type { Metadata } from "next";
import Link from "next/link";
import { businessApplications } from "@/data/catalog";
import { PageTransition } from "@/components/animation/PageTransition";
import { Icon } from "@/lib/icons";
import { tint } from "@/lib/utils";
import { CTASection } from "@/components/shared/CTASection";
import { site } from "@/data/site";
const title = "Business Applications | Melorite";
const description = "Seven connected Business Applications for CRM & Growth, Finance, HRMS, Commerce, Projects, Service, and Procurement & Inventory.";
export const metadata: Metadata = { title, description, alternates: { canonical: "/business-applications" }, openGraph: { title, description, url: "/business-applications" } };
export default function BusinessApplicationsPage() { return <PageTransition><section className="border-b border-line bg-paper pb-20 pt-[132px] md:pt-[152px]"><div className="container-x max-w-5xl"><p className="text-[13px] font-semibold uppercase tracking-[.09em] text-brand">Business Applications</p><h1 className="text-h1 mt-4 max-w-[16ch] text-navy">The work your business needs, connected.</h1><p className="text-lead mt-6 max-w-[60ch] text-muted">Seven focused applications bring essential operations into one Melorite workspace. Start where you need to, and connect the rest as you grow.</p></div></section><section className="section-y"><div className="container-x"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{businessApplications.map((app, index) => <Link key={app.slug} href={`/business-applications/${app.slug}`} className={`group border border-line bg-white p-7 transition duration-300 hover:-translate-y-0.5 hover:shadow-soft ${index === 0 ? "md:col-span-2 xl:col-span-2" : ""}`}><span className="grid size-11 place-items-center rounded-xl" style={{ background: tint(app.accent,.1), color: app.accent }}><Icon name={app.icon} className="size-5" /></span><p className="mt-7 text-sm font-semibold text-navy">{app.name}</p><p className="mt-2 text-sm leading-relaxed text-muted">{app.eyebrow}</p><p className="mt-5 max-w-[55ch] text-[15px] leading-relaxed text-slate-600">{app.description}</p><span className="mt-6 inline-block text-sm font-semibold text-brand">Explore application →</span></Link>)}</div></div></section><CTASection title={["Build the workspace", "your business needs."]} description="See how the right combination of Melorite applications can work together." primary={{ label: "Book a Demo", href: site.demoHref }} secondary={{ label: "Explore the Platform", href: "/platform" }} /></PageTransition>; }
