import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, PhoneCall, Sparkles } from "lucide-react";
import { businessApplications, industrySolutions } from "@/data/catalog";
import { detailsFor } from "@/data/catalog-content";
import { Icon } from "@/lib/icons";
import { tint } from "@/lib/utils";
import { PageTransition } from "@/components/animation/PageTransition";
import { ButtonLink } from "@/components/shared/Button";
import { AIDemo } from "@/components/ai/AIDemo";
import { ConnectedWorkflow } from "@/components/catalogue/ConnectedWorkflow";
import { site } from "@/data/site";

const title = "Business Applications & AI";
const description = "Explore seven connected business applications, Melorite AI and six industry solutions in one business platform.";
export const metadata: Metadata = { title, description, alternates: { canonical: "/products" }, openGraph: { title, description, url: "/products", images: ["/products/opengraph-image"] }, twitter: { card: "summary_large_image" } };

function MiniProduct({ slug, accent }: { slug: string; accent: string }) {
  const detail = detailsFor(slug);
  if (slug === "crm-growth") return <div className="grid grid-cols-3 gap-2">{detail.records.map((r,i)=><div key={r.primary} className="rounded-lg border border-line bg-white p-2"><i className="mb-2 block h-1 rounded-full" style={{ width: `${55+i*18}%`, background: accent }}/><p className="truncate text-[9px] font-semibold text-navy">{r.primary}</p><p className="mt-1 text-[8px] text-muted">{r.value}</p></div>)}</div>;
  if (slug === "finance") return <div className="flex h-20 items-end gap-2 rounded-lg border border-line bg-white p-3">{[42,70,55,88,64,92,76].map((h,i)=><i key={i} className="flex-1 rounded-t" style={{ height: `${h}%`, background: i>4 ? accent : tint(accent,.2) }}/>)}</div>;
  if (slug === "hrms") return <div className="flex gap-2">{detail.records.map(r=><div key={r.primary} className="flex-1 rounded-lg border border-line bg-white p-2"><span className="grid size-6 place-items-center rounded-full text-[8px] font-semibold" style={{ background:tint(accent,.12),color:accent }}>{r.primary.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><p className="mt-2 truncate text-[9px] font-semibold text-navy">{r.primary}</p><p className="mt-1 text-[8px] text-muted">{r.value}</p></div>)}</div>;
  return <div className="overflow-hidden rounded-lg border border-line bg-white">{detail.records.map(r=><div key={r.primary} className="grid grid-cols-[1fr_auto] gap-3 border-b border-line p-2 last:border-0"><div><p className="truncate text-[9px] font-semibold text-navy">{r.primary}</p><p className="mt-0.5 truncate text-[8px] text-muted">{r.secondary}</p></div><span className="text-[8px] font-medium" style={{color:accent}}>{r.status}</span></div>)}</div>;
}

export default function ProductsPage() {
  return <PageTransition>
    <section className="relative overflow-hidden border-b border-line bg-paper pb-20 pt-[132px] md:pb-24 md:pt-[156px]"><div className="absolute inset-0 bg-[radial-gradient(70%_70%_at_80%_20%,#e9f1ff,transparent)]" aria-hidden/><div className="container-x relative grid items-end gap-12 lg:grid-cols-[1fr_.8fr]"><div><p className="text-[12px] font-semibold uppercase tracking-[.11em] text-brand">Melorite products</p><h1 className="text-h1 mt-5 max-w-[15ch] text-navy">Everything your business needs. Connected by design.</h1><p className="text-lead mt-6 max-w-[58ch] text-muted">Melorite combines core business applications, AI and industry-specific solutions within one connected platform.</p><div className="mt-9 flex flex-wrap gap-3"><ButtonLink href="#applications" size="lg" arrow>Explore Products</ButtonLink><ButtonLink href={site.demoHref} size="lg" variant="secondary">Talk to us</ButtonLink></div></div><div className="hidden grid-cols-2 gap-2 lg:grid">{businessApplications.slice(0,4).map(app=><div key={app.slug} className="rounded-xl border border-line bg-white p-4 shadow-soft"><div className="flex items-center gap-2"><Icon name={app.icon} className="size-4" style={{color:app.accent}}/><span className="text-[11px] font-semibold text-navy">{app.name}</span></div><div className="mt-3"><MiniProduct slug={app.slug} accent={app.accent}/></div></div>)}</div></div></section>

    <section className="section-y bg-white"><div className="container-x"><div className="grid items-end gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[12px] font-semibold uppercase tracking-[.1em] text-brand">Connected platform</p><h2 className="text-h2 mt-3 max-w-[12ch] text-navy">One operation, seen from every team.</h2></div><p className="max-w-[58ch] text-[16px] leading-relaxed text-muted">A customer record can become an order, invoice, delivery project and service history without each team rebuilding the context from scratch. Melorite AI works across the same permitted records.</p></div><div className="mt-12 overflow-hidden rounded-2xl border border-line bg-paper p-4 md:p-7"><div className="grid gap-3 md:grid-cols-[1fr_auto_1fr_auto_1fr_auto_1fr] md:items-center">{[businessApplications[0],businessApplications[1],businessApplications[4],businessApplications[5]].map((app,index)=><div key={app.slug} className="contents"><Link href={`/products/${app.slug}`} className="rounded-xl border border-line bg-white p-4 transition hover:-translate-y-0.5 hover:shadow-soft"><div className="flex items-center gap-2"><Icon name={app.icon} className="size-4" style={{color:app.accent}}/><span className="text-[11px] font-semibold text-navy">{app.name}</span></div><p className="mt-4 text-[9px] uppercase tracking-wide text-muted">{detailsFor(app.slug).workspaceLabel}</p><p className="mt-1 text-[12px] font-medium text-navy">{detailsFor(app.slug).records[0].primary}</p></Link>{index < 3 && <span className="hidden text-center text-lg text-slate-300 md:block">→</span>}</div>)}</div><div className="mt-3 flex items-center justify-between rounded-xl bg-navy px-4 py-3 text-white"><div className="flex items-center gap-2"><Sparkles className="size-4 text-blue-300"/><span className="text-[11px] font-semibold">Melorite AI across the connected record</span></div><span className="hidden text-[10px] text-slate-400 sm:inline">Analyse · Recommend · Act with approval</span></div></div></div></section>

    <section id="applications" className="scroll-mt-24 section-y bg-paper"><div className="container-x"><p className="text-[12px] font-semibold uppercase tracking-[.1em] text-brand">Business applications</p><h2 className="text-h2 mt-3 max-w-[14ch] text-navy">Built to stand alone. Designed to work together.</h2><div className="mt-14 grid auto-rows-[minmax(260px,auto)] gap-4 md:grid-cols-12">{businessApplications.map((app,index)=>{const spans=["md:col-span-8","md:col-span-4","md:col-span-4","md:col-span-8","md:col-span-6","md:col-span-6","md:col-span-12"];return <Link key={app.slug} href={`/products/${app.slug}`} className={`group overflow-hidden rounded-2xl border border-line bg-white p-6 transition duration-300 hover:-translate-y-0.5 hover:shadow-ui ${spans[index]}`}><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl" style={{background:tint(app.accent,.1),color:app.accent}}><Icon name={app.icon} className="size-5"/></span><ArrowUpRight className="size-4 text-slate-300 transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5 group-hover:text-brand"/></div><div className={`${index===6 ? "mt-7 grid gap-6 md:grid-cols-[.7fr_1.3fr] md:items-end" : "mt-7"}`}><div><h3 className="text-h3 text-navy">{app.name}</h3><p className="mt-3 max-w-[48ch] text-[14px] leading-relaxed text-muted">{app.description}</p><div className="mt-5 flex flex-wrap gap-2">{app.modules.slice(0,4).map(m=><span key={m} className="text-[10px] font-medium text-slate-500">{m}</span>)}</div></div><div className={`${index===6 ? "mt-0" : "mt-7"} rounded-xl bg-paper p-3`}><MiniProduct slug={app.slug} accent={app.accent}/></div></div></Link>})}</div></div></section>

    <section className="section-y bg-white"><div className="container-x"><p className="text-[12px] font-semibold uppercase tracking-[.1em] text-brand">Connected workflow</p><h2 className="text-h2 mt-3 max-w-[14ch] text-navy">See which application owns each stage.</h2><p className="mt-5 max-w-[58ch] text-[16px] leading-relaxed text-muted">Select a stage to see how customer context moves from demand through delivery and ongoing service.</p><ConnectedWorkflow/></div></section>

    <section className="section-y bg-[#f5f3ff]">
      <div className="container-x">
        <div className="grid items-end gap-8 lg:grid-cols-[.8fr_1.2fr]">
          <div><p className="text-[12px] font-semibold uppercase tracking-[.1em] text-[#7c3aed]">Melorite AI</p><h2 className="text-h2 mt-3 max-w-[12ch] text-navy">Intelligence inside the work.</h2></div>
          <p className="max-w-[58ch] text-[16px] leading-relaxed text-muted">AI Agent helps teams understand and act across permitted business context. AI Calling turns configured conversations into structured outcomes and follow-through.</p>
        </div>
        <div className="mt-12 grid gap-5 lg:grid-cols-2">
          <div><AIDemo/><Link href="/ai/agent" className="mt-5 inline-flex items-center gap-1 text-[13px] font-semibold text-brand">Explore AI Agent <ArrowUpRight className="size-3.5"/></Link></div>
          <div>
            <div className="overflow-hidden rounded-xl border border-line bg-white shadow-ui">
              <div className="flex items-center justify-between border-b border-line bg-surface-warm px-5 py-3.5"><span className="text-[13px] font-medium text-navy">AI Calling</span><span className="flex items-center gap-1.5 text-[11px] text-[#a0278c]"><i className="size-1.5 animate-pulse rounded-full bg-[#a0278c]"/>Live · 02:14</span></div>
              <div className="grid md:grid-cols-[1.1fr_.9fr]">
                <div className="border-b border-line p-6 md:border-b-0 md:border-r"><div className="space-y-4"><p className="max-w-[85%] rounded-lg bg-[#f5f0ff] px-3 py-2 text-[12px] leading-relaxed text-slate-700"><strong className="block text-navy">AI</strong>What would you like help with today?</p><p className="ml-auto max-w-[85%] rounded-lg bg-slate-100 px-3 py-2 text-[12px] leading-relaxed text-slate-700"><strong className="block text-navy">Customer</strong>We need a clearer view of finance and billing.</p></div><div className="mt-7 flex h-6 items-center gap-1">{[6,14,20,9,24,13,7,18,12,5,16,10,21,8,14].map((h,i)=><i key={i} className="w-1 rounded-full bg-[#a0278c]/30" style={{height:h}}/>)}</div></div>
                <div className="p-6"><PhoneCall className="size-4 text-[#a0278c]"/><p className="mt-4 text-[11px] text-muted">Structured outcome</p><p className="mt-1 text-[14px] font-semibold text-navy">Finance enquiry qualified</p><div className="mt-5 space-y-3 text-[11px] text-muted"><p>Contact matched to CRM</p><p>Demo time proposed</p><p>Summary ready for review</p></div></div>
              </div>
            </div>
            <Link href="/ai/calling" className="mt-5 inline-flex items-center gap-1 text-[13px] font-semibold text-[#a0278c]">Explore AI Calling <ArrowUpRight className="size-3.5"/></Link>
          </div>
        </div>
      </div>
    </section>

    <section className="section-y bg-white"><div className="container-x"><p className="text-[12px] font-semibold uppercase tracking-[.1em] text-brand">Industry solutions</p><h2 className="text-h2 mt-3 max-w-[15ch] text-navy">Purpose-built workflows on the same platform.</h2><div className="mt-12 grid gap-x-8 border-t border-line md:grid-cols-2 lg:grid-cols-3">{industrySolutions.map(solution=><Link key={solution.slug} href={`/solutions/${solution.slug}`} className="group border-b border-line py-7"><div className="flex items-start justify-between"><Icon name={solution.icon} className="size-5" style={{color:solution.accent}}/><ArrowUpRight className="size-4 text-slate-300 group-hover:text-brand"/></div><h3 className="mt-5 text-[16px] font-semibold text-navy">{solution.name}</h3><p className="mt-2 text-[13px] leading-relaxed text-muted">{solution.description}</p><p className="mt-5 text-[10px] font-semibold uppercase tracking-wide" style={{color:solution.accent}}>{solution.workflow.join(" → ")}</p></Link>)}</div></div></section>

    <section className="bg-navy py-20 text-white md:py-24"><div className="container-x max-w-5xl text-center"><p className="text-[12px] font-semibold uppercase tracking-[.1em] text-blue-300">Build with Melorite</p><h2 className="text-h2 mx-auto mt-4 max-w-[17ch] text-white">Build the platform your business actually needs.</h2><p className="mx-auto mt-5 max-w-[54ch] text-[16px] leading-relaxed text-slate-300">Start with the applications that solve today’s work. Connect more when the business is ready.</p><div className="mt-8 flex justify-center gap-3"><ButtonLink href={site.demoHref} size="lg" variant="light" arrow>Explore Melorite</ButtonLink><ButtonLink href="/contact" size="lg" variant="outline-light">Talk to us</ButtonLink></div></div></section>
  </PageTransition>;
}
