import Link from "next/link";
import { ArrowUpRight, Check, LockKeyhole, Network, ShieldCheck, Sparkles } from "lucide-react";
import { type Offering } from "@/data/catalog";
import { detailsFor } from "@/data/catalog-content";
import { Icon } from "@/lib/icons";
import { tint } from "@/lib/utils";
import { ButtonLink } from "@/components/shared/Button";
import { site } from "@/data/site";
import { CatalogueWorkspace } from "@/components/catalogue/CatalogueWorkspace";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

type Props = { offering: Offering; kind: "product" | "solution" | "ai"; hero?: string; aiCalling?: boolean };

function StructuredData({ offering, kind, path }: { offering: Offering; kind: Props["kind"]; path: string }) {
  const details = detailsFor(offering.slug);
  const group = kind === "solution" ? "Solutions" : kind === "ai" ? "Melorite AI" : "Products";
  const groupPath = kind === "solution" ? "/solutions" : kind === "ai" ? "/ai" : "/products";
  const graph: Record<string, unknown>[] = [
    { "@type": "BreadcrumbList", itemListElement: [{ "@type": "ListItem", position: 1, name: "Home", item: site.url }, { "@type": "ListItem", position: 2, name: group, item: `${site.url}${groupPath}` }, { "@type": "ListItem", position: 3, name: offering.name, item: `${site.url}${path}` }] },
    { "@type": "FAQPage", mainEntity: details.faqs.map((item) => ({ "@type": "Question", name: item.question, acceptedAnswer: { "@type": "Answer", text: item.answer } })) },
  ];
  if (kind !== "solution") graph.push({ "@type": "SoftwareApplication", name: offering.name, applicationCategory: "BusinessApplication", operatingSystem: "Web", description: offering.description, url: `${site.url}${path}` });
  return <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({ "@context": "https://schema.org", "@graph": graph }) }} />;
}

export function OfferingStory({ offering, kind, hero }: Props) {
  const details = detailsFor(offering.slug);
  const group = kind === "solution" ? "Solutions" : kind === "ai" ? "Melorite AI" : "Products";
  const groupPath = kind === "solution" ? "/solutions" : kind === "ai" ? "/ai" : "/products";
  const pagePath = kind === "solution" ? `/solutions/${offering.slug}` : kind === "ai" ? `/ai/${offering.slug}` : `/products/${offering.slug}`;
  const isIndustry = kind === "solution";

  return <>
    <StructuredData offering={offering} kind={kind} path={pagePath} />
    <section className="relative overflow-hidden border-b border-line bg-paper pb-20 pt-[124px] md:pb-24 md:pt-[148px]">
      <div className="absolute inset-y-0 right-0 hidden w-[42%] opacity-60 lg:block" style={{ background: `radial-gradient(circle at 70% 40%, ${tint(offering.accent,.15)}, transparent 62%)` }} aria-hidden />
      <div className="container-x relative grid items-end gap-12 lg:grid-cols-[1.15fr_.85fr]">
        <div>
          <nav aria-label="Breadcrumb" className="mb-8 text-[13px] text-muted"><ol className="flex flex-wrap items-center gap-2"><li><Link href="/" className="rounded-sm hover:text-navy">Home</Link></li><li aria-hidden>/</li><li><Link href={groupPath} className="rounded-sm hover:text-navy">{group}</Link></li><li aria-hidden>/</li><li aria-current="page" className="text-navy">{offering.name}</li></ol></nav>
          <div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl" style={{ background: tint(offering.accent,.1), color: offering.accent }}><Icon name={offering.icon} className="size-5" /></span><p className="text-[12px] font-semibold uppercase tracking-[.11em]" style={{ color: offering.accent }}>{offering.eyebrow}</p></div>
          <h1 className="text-h1 mt-7 max-w-[16ch] text-navy">{hero ?? details.hero}</h1>
          <p className="text-lead mt-6 max-w-[60ch] text-muted">{offering.description}</p>
          <div className="mt-9 flex flex-wrap gap-3"><ButtonLink href={site.demoHref} size="lg" arrow>Book a Demo</ButtonLink><ButtonLink href="#workspace" size="lg" variant="secondary">See the product</ButtonLink></div>
        </div>
        <div className="hidden border-l border-line pl-8 lg:block"><p className="text-[12px] font-semibold uppercase tracking-[.1em] text-muted">What this connects</p><ul className="mt-5 space-y-3">{offering.modules.slice(0,6).map((module) => <li key={module} className="flex items-center gap-3 text-[14px] font-medium text-navy"><span className="size-1.5 rounded-full" style={{ background: offering.accent }}/>{module}</li>)}</ul></div>
      </div>
    </section>

    <nav aria-label={`${offering.name} sections`} className="sticky top-16 z-30 hidden border-b border-line bg-white/95 backdrop-blur md:block"><div className="container-x flex h-12 items-center gap-7 overflow-x-auto text-[12px] font-medium text-muted"><span className="mr-auto shrink-0 font-semibold text-navy">{offering.name}</span><a href="#workspace" className="shrink-0 hover:text-brand">Workspace</a><a href="#capabilities" className="shrink-0 hover:text-brand">Capabilities</a><a href="#ai" className="shrink-0 hover:text-brand">AI</a><a href="#connections" className="shrink-0 hover:text-brand">Connections</a><a href="#faq" className="shrink-0 hover:text-brand">FAQ</a></div></nav>

    <section id="workspace" className="scroll-mt-28 section-y bg-white"><div className="container-x"><div className="grid items-end gap-8 lg:grid-cols-[.85fr_1.15fr]"><div><p className="text-[12px] font-semibold uppercase tracking-[.1em]" style={{ color: offering.accent }}>{isIndustry ? "Industry workspace" : "Product workspace"}</p><h2 className="text-h2 mt-3 max-w-[13ch] text-navy">The work, not a placeholder.</h2></div><p className="max-w-[60ch] text-[16px] leading-relaxed text-muted">{details.proposition}</p></div><div className="mt-12"><CatalogueWorkspace offering={offering} details={details}/></div></div></section>

    <section className="section-y bg-navy text-white"><div className="container-x grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[12px] font-semibold uppercase tracking-[.1em]" style={{ color: tint(offering.accent,.72) }}>How work moves</p><h2 className="text-h2 mt-3 max-w-[12ch] text-white">One journey. Clear ownership.</h2><p className="mt-5 max-w-[44ch] text-[15px] leading-relaxed text-slate-300">Each stage keeps its record, status and next action connected instead of handing the work to another spreadsheet.</p></div><ol className="relative grid gap-0 sm:grid-cols-5">{offering.workflow.map((step,index) => <li key={step} className="relative border-l border-white/15 py-4 pl-5 sm:border-l-0 sm:border-t sm:py-6 sm:pl-0 sm:pr-4"><span className="absolute -left-1 top-6 size-2 rounded-full ring-4 ring-navy sm:left-0 sm:-top-1" style={{ background: offering.accent }}/><span className="text-[10px] font-medium text-white/45">0{index+1}</span><p className="mt-3 text-[13px] font-medium text-white">{step}</p></li>)}</ol></div></section>

    <section id="capabilities" className="scroll-mt-28 section-y bg-paper"><div className="container-x"><div className="max-w-3xl"><p className="text-[12px] font-semibold uppercase tracking-[.1em] text-brand">Core capabilities</p><h2 className="text-h2 mt-3 text-navy">Built around the work that matters.</h2><p className="mt-5 text-[16px] leading-relaxed text-muted">The current catalogue groups related records and workflows into a focused operating surface. Availability can be configured for the needs and entitlements of each workspace.</p></div><div className="mt-14 grid gap-px overflow-hidden rounded-2xl border border-line bg-line lg:grid-cols-3">{details.featureGroups.map((feature,index) => <article key={feature.title} className="bg-white p-6 md:p-8"><span className="text-[11px] font-semibold" style={{ color: offering.accent }}>0{index+1}</span><h3 className="mt-5 text-h3 text-navy">{feature.title}</h3><p className="mt-3 text-[14px] leading-relaxed text-muted">{feature.description}</p><ul className="mt-7 space-y-3 border-t border-line pt-6">{feature.items.map((item) => <li key={item} className="flex gap-3 text-[13px] text-slate-700"><Check className="mt-0.5 size-3.5 shrink-0" style={{ color: offering.accent }}/>{item}</li>)}</ul></article>)}</div></div></section>

    <section className="section-y bg-white"><div className="container-x grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-[12px] font-semibold uppercase tracking-[.1em] text-brand">Built for the team</p><h2 className="text-h2 mt-3 max-w-[12ch] text-navy">A useful view for every role.</h2></div><div className="border-t border-line">{details.roles.map((role,index) => <div key={role.title} className="grid gap-3 border-b border-line py-6 sm:grid-cols-[36px_180px_1fr]"><span className="text-[11px] text-muted">0{index+1}</span><h3 className="text-[15px] font-semibold text-navy">{role.title}</h3><p className="text-[14px] leading-relaxed text-muted">{role.description}</p></div>)}</div></div></section>

    <section id="ai" className="scroll-mt-28 section-y bg-[#f5f3ff]"><div className="container-x grid items-center gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><div className="flex items-center gap-2 text-[#7c3aed]"><Sparkles className="size-4"/><p className="text-[12px] font-semibold uppercase tracking-[.1em]">Melorite AI</p></div><h2 className="text-h2 mt-4 max-w-[12ch] text-navy">Ask with context. Act with control.</h2><p className="mt-5 max-w-[46ch] text-[15px] leading-relaxed text-muted">AI works with the permitted records and workflows inside Melorite. It shows its result for review before beginning actions that require confirmation.</p></div><div className="overflow-hidden rounded-2xl border border-violet-200 bg-white shadow-ui"><div className="border-b border-line px-5 py-4"><p className="text-[11px] font-medium text-muted">Ask Melorite</p><p className="mt-2 text-[16px] font-medium text-navy">“{details.aiPrompt}”</p></div><div className="p-5"><div className="flex gap-3"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-violet-100 text-violet-700"><Sparkles className="size-4"/></span><div><p className="text-[13px] font-semibold text-navy">Analysis ready for review</p><p className="mt-2 text-[13px] leading-relaxed text-muted">{details.aiResult}</p></div></div><div className="mt-5 flex flex-wrap gap-2 border-t border-line pt-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] text-slate-600">Permission aware</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] text-slate-600">Linked to records</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] text-slate-600">Human confirmation</span></div></div></div></div></section>

    <section id="connections" className="scroll-mt-28 section-y bg-white"><div className="container-x"><div className="grid gap-8 lg:grid-cols-[.8fr_1.2fr]"><div><Network className="size-5 text-brand"/><h2 className="text-h2 mt-5 max-w-[12ch] text-navy">More useful when connected.</h2></div><div className="grid gap-px overflow-hidden rounded-2xl border border-line bg-line sm:grid-cols-3">{details.connections.map((connection) => <Link key={connection.href} href={connection.href} className="group bg-white p-6 transition-colors hover:bg-brand-50"><p className="text-[14px] font-semibold text-navy">{connection.name}</p><p className="mt-3 text-[13px] leading-relaxed text-muted">{connection.description}</p><span className="mt-6 inline-flex items-center gap-1 text-[12px] font-semibold text-brand">Explore <ArrowUpRight className="size-3.5 transition-transform group-hover:translate-x-0.5 group-hover:-translate-y-0.5"/></span></Link>)}</div></div><div className="mt-16 grid gap-10 border-t border-line pt-10 lg:grid-cols-2"><div><p className="text-[12px] font-semibold uppercase tracking-[.1em] text-brand">Integration possibilities</p><div className="mt-5 flex flex-wrap gap-2">{details.integrations.map(item => <span key={item} className="rounded-full border border-line bg-paper px-3 py-2 text-[12px] font-medium text-slate-700">{item}</span>)}</div></div><div><p className="text-[12px] font-semibold uppercase tracking-[.1em] text-brand">Platform controls</p><div className="mt-5 grid gap-4 sm:grid-cols-2"><div className="flex gap-3"><LockKeyhole className="mt-0.5 size-4 shrink-0 text-brand"/><p className="text-[13px] leading-relaxed text-muted"><strong className="block text-navy">Role-aware access</strong>Keep records and actions aligned to workspace permissions.</p></div><div className="flex gap-3"><ShieldCheck className="mt-0.5 size-4 shrink-0 text-brand"/><p className="text-[13px] leading-relaxed text-muted"><strong className="block text-navy">Governed workflows</strong>Keep ownership, status and important activity visible.</p></div></div></div></div></div></section>

    <section id="faq" className="scroll-mt-28 section-y border-t border-line bg-paper"><div className="container-x grid gap-12 lg:grid-cols-[.75fr_1.25fr]"><div><p className="text-[12px] font-semibold uppercase tracking-[.1em] text-brand">Frequently asked questions</p><h2 className="text-h2 mt-3 text-navy">What teams usually ask.</h2></div><Accordion type="single" collapsible className="border-t border-line">{details.faqs.map((item,index) => <AccordionItem key={item.question} value={`item-${index}`}><AccordionTrigger>{item.question}</AccordionTrigger><AccordionContent>{item.answer}</AccordionContent></AccordionItem>)}</Accordion></div></section>

    <section className="bg-navy py-20 text-white md:py-24"><div className="container-x max-w-5xl text-center"><p className="text-[12px] font-semibold uppercase tracking-[.1em] text-blue-300">See {offering.name} in context</p><h2 className="text-h2 mx-auto mt-4 max-w-[18ch] text-white">{details.cta}</h2><p className="mx-auto mt-5 max-w-[55ch] text-[16px] leading-relaxed text-slate-300">Walk through the workflows, records and connected applications that matter to your organization.</p><div className="mt-8 flex flex-wrap justify-center gap-3"><ButtonLink href={site.demoHref} size="lg" variant="light" arrow>Book a Demo</ButtonLink><ButtonLink href="/contact" size="lg" variant="outline-light">Talk to us</ButtonLink></div></div></section>
  </>;
}
